server:
  port: 7878
spring:
  application:
    name: DataCollectionModule02
  config:
    import: "optional:configserver:"
eureka:
  client:
    service-url:
       default-zone: http://localhost:8761/eureka/

