server:
  port: 9797
spring:
  boot:
    admin:
      client:
         url: http://localhost:9999
  application:
    name: AdminApiModule04
  config:
    import: "optional:configserver:"
eureka:
  client:
   service-url:
      default-zone: http://localhost:8761/eureka/
      
plan:
 module:
  messages:
    save-success:  Plan is saved with id value
    save-failure:  Plan is not saved with Value
    find-by-id-failure:  Plan is not found
    update-success:  Plan is updated
    update-failure:  Plan is not found for updation
    delete-success:  Plan is deleted
    delete-failure:  Plan is not found for deletion
    status-change-success:  Plan Status is changed
    status-change-failure:  Plan is not found for status change
#active all actuator
management:
  endpoint:
    env: 
      enabled: true
      show-values: always
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
